unit ufrmRPA;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  Db, ADODB, Qrctrls, QuickRpt, ExtCtrls;

type
  TfrmRPA = class(TForm)
    QuickRep1: TQuickRep;
    QRBand1: TQRBand;
    QRBand2: TQRBand;
    QRDBText1: TQRDBText;
    QRShape1: TQRShape;
    QRShape2: TQRShape;
    QRShape4: TQRShape;
    QRShape5: TQRShape;
    QRShape6: TQRShape;
    QRShape7: TQRShape;
    QRLabel1: TQRLabel;
    QRLabel2: TQRLabel;
    QRLabel3: TQRLabel;
    QRShape3: TQRShape;
    QRLabel4: TQRLabel;
    QRShape8: TQRShape;
    QRLabel5: TQRLabel;
    QRShape9: TQRShape;
    QRShape10: TQRShape;
    qrParametro: TADOQuery;
    qrParametroPAR_ID: TAutoIncField;
    qrParametroPAR_NOME: TStringField;
    qrParametroPAR_RAZA: TStringField;
    qrParametroPAR_CNPJ: TStringField;
    qrParametroPAR_INSC: TStringField;
    qrParametroPAR_ENDERECO: TStringField;
    qrParametroPAR_ENDERECO_COMPL: TStringField;
    qrParametroPAR_ENDERECO_BAIRRO: TStringField;
    qrParametroPAR_UF_SIGLA: TStringField;
    qrParametroPAR_CEP: TStringField;
    qrParametroPAR_TEL: TStringField;
    qrParametroPAR_FAX: TStringField;
    qrParametroPAR_EMAIL: TStringField;
    qrParametroAR_ID: TIntegerField;
    qrParametroMUN_ID: TIntegerField;
    qrParametroAR_ID_OPER: TIntegerField;
    qrParametroULT_TAG: TIntegerField;
    qrParametroPALLET_M2: TFloatField;
    qrParametroCO_SER_ID: TIntegerField;
    qrParametroEN_SER_ID: TIntegerField;
    qrParametroFLAGTELA: TStringField;
    qrParametroFLAGTELA2: TStringField;
    qrParametroFLAGTELA3: TStringField;
    qrParametroCLIN_ID: TIntegerField;
    qrParametroVERSAO: TStringField;
    qrParametroFLAGTELA_USUARIO: TStringField;
    qrParametroFLAGTELA_DATA: TDateTimeField;
    qrParametroFLAGTELA2_USUARIO: TStringField;
    qrParametroFLAGTELA2_DATA: TDateTimeField;
    qrParametroPORTA: TIntegerField;
    qrParametroHOST: TStringField;
    qrParametroCAMINHO: TStringField;
    qrParametroULT_FATURA: TIntegerField;
    qrParametroULT_NF: TIntegerField;
    qrParametroULT_CONH: TIntegerField;
    qrParametroAR_ID_AVARIA: TIntegerField;
    qrParametroULT_MINUTA: TIntegerField;
    qrParametroULT_NFPROV: TIntegerField;
    qrParametroULT_CONHPROV: TIntegerField;
    qrParametroULT_MINUTAPROV: TIntegerField;
    qrParametroCAMINHO_MATRICIAL: TStringField;
    qrParametroCAMINHO_MATRICIAL_FATURA: TStringField;
    qrParametroCAMINHO_MATRICIAL_CONH: TStringField;
    qrParametroDATA: TDateTimeField;
    qrParametroConnectionString: TStringField;
    qrParametroIBGE_ID: TIntegerField;
    qrParametroNUMERO: TIntegerField;
    qrParametroLOGO: TBlobField;
    qrParametroNF_SERVICO: TIntegerField;
    qrParametroALIQ_ISS: TFloatField;
    qrParametroNF_SERVICO_PROV: TIntegerField;
    qrParametroALIQ_ISS_NFS_OE: TFloatField;
    qrParametroDATA_FRETE_FECHAMENTO: TDateTimeField;
    QRDBText2: TQRDBText;
    QRDBText3: TQRDBText;
    QRLabel6: TQRLabel;
    QRLabel7: TQRLabel;
    QRLabel8: TQRLabel;
    QRShape11: TQRShape;
    QRShape12: TQRShape;
    lbValorExtenso: TQRLabel;
    QRShape13: TQRShape;
    QRLabel10: TQRLabel;
    QRShape14: TQRShape;
    QRLabel9: TQRLabel;
    QRShape15: TQRShape;
    QRLabel11: TQRLabel;
    QRShape16: TQRShape;
    QRLabel12: TQRLabel;
    QRShape17: TQRShape;
    QRLabel13: TQRLabel;
    QRShape18: TQRShape;
    QRLabel14: TQRLabel;
    QRShape19: TQRShape;
    QRLabel15: TQRLabel;
    QRShape20: TQRShape;
    QRShape21: TQRShape;
    QRShape22: TQRShape;
    QRLabel16: TQRLabel;
    QRShape23: TQRShape;
    QRMemo1: TQRMemo;
    QRShape24: TQRShape;
    QRLabel17: TQRLabel;
    QRShape25: TQRShape;
    QRShape26: TQRShape;
    QRLabel18: TQRLabel;
    QRLabel19: TQRLabel;
    QRShape27: TQRShape;
    QRLabel20: TQRLabel;
    QRShape28: TQRShape;
    QRShape29: TQRShape;
    QRShape30: TQRShape;
    QRShape31: TQRShape;
    QRLabel21: TQRLabel;
    QRLabel22: TQRLabel;
    QRShape32: TQRShape;
    QRLabel23: TQRLabel;
    QRShape33: TQRShape;
    QRLabel24: TQRLabel;
    QRShape34: TQRShape;
    QRShape35: TQRShape;
    QRShape36: TQRShape;
    QRShape37: TQRShape;
    QRLabel25: TQRLabel;
    QRLabel26: TQRLabel;
    QRLabel27: TQRLabel;
    QRLabel28: TQRLabel;
    QRLabel29: TQRLabel;
    QRLabel30: TQRLabel;
    QRLabel31: TQRLabel;
    QRLabel32: TQRLabel;
    QRLabel33: TQRLabel;
    QRLabel34: TQRLabel;
    QRLabel35: TQRLabel;
    QRShape38: TQRShape;
    QRShape39: TQRShape;
    QRShape40: TQRShape;
    QRLabel36: TQRLabel;
    QRLabel37: TQRLabel;
    QRLabel38: TQRLabel;
    QRLabel39: TQRLabel;
    QRLabel40: TQRLabel;
    QRLabel41: TQRLabel;
    QRLabel42: TQRLabel;
    QRLabel43: TQRLabel;
    QRLabel44: TQRLabel;
    QRLabel45: TQRLabel;
    QRLabel46: TQRLabel;
    QRShape41: TQRShape;
    QRShape42: TQRShape;
    QRShape43: TQRShape;
    QRShape44: TQRShape;
    QRShape45: TQRShape;
    QRLabel47: TQRLabel;
    QRShape46: TQRShape;
    QRShape47: TQRShape;
    lbTotal1: TQRLabel;
    QRLabel48: TQRLabel;
    lbValorPrestado: TQRLabel;
    QRLabel50: TQRLabel;
    lbValorPrestado2: TQRLabel;
    lbVlrAdiantamento: TQRLabel;
    lbVlrOutros: TQRLabel;
    lbIRRF: TQRLabel;
    lbSESTSENAT: TQRLabel;
    lbINSS: TQRLabel;
    lbTotal2: TQRLabel;
    QRDBText4: TQRDBText;
    qrParametroID: TAutoIncField;
    qrParametroCOD_UF: TIntegerField;
    qrParametroUF: TStringField;
    qrParametroCOD_MUN: TIntegerField;
    qrParametroMUNICIPIO: TStringField;
    QRDBText5: TQRDBText;
    qrTransp: TADOQuery;
    qrTranspTRANS_ID: TAutoIncField;
    qrTranspTRANS_FANTASIA: TStringField;
    qrTranspTRANS_RAZA: TStringField;
    qrTranspTRANS_CNPJ: TStringField;
    qrTranspTRANS_INSCRICAO: TStringField;
    qrTranspTRANS_ENDERECO: TStringField;
    qrTranspTRANS_ENDERECO_COMPL: TStringField;
    qrTranspTRANS_ENDERECO_BAIRRO: TStringField;
    qrTranspTRANS_MUNICIPIO: TStringField;
    qrTranspTRANS_CEP: TStringField;
    qrTranspUF_SIGLA: TStringField;
    qrTranspTRANS_TEL: TStringField;
    qrTranspTRANS_TEL2: TStringField;
    qrTranspTRANS_FAX: TStringField;
    qrTranspTRANS_EMAIL: TStringField;
    qrTranspTRANS_CONTATO: TStringField;
    qrTranspTRANS_FLAG: TStringField;
    qrTranspCON_CODI: TStringField;
    qrTranspMUN_ID: TIntegerField;
    qrTranspTRANS_PESSOA: TStringField;
    qrTranspTRANS_REDES: TStringField;
    qrTranspPIS: TStringField;
    qrTranspIBGE_ID: TIntegerField;
    lbData: TQRLabel;
    QRDBText6: TQRDBText;
    qrTranspMOT_ID: TAutoIncField;
    qrTranspTRANS_ID_1: TIntegerField;
    qrTranspMOT_NOME: TStringField;
    qrTranspMOT_ENDERECO: TStringField;
    qrTranspMOT_MUNICIPIO: TStringField;
    qrTranspMOT_CEP: TStringField;
    qrTranspUF_SIGLA_1: TStringField;
    qrTranspMOT_CPF: TStringField;
    qrTranspMOT_RG: TStringField;
    qrTranspMOT_DT_NASC: TDateTimeField;
    qrTranspMOT_RG_ORGAO: TStringField;
    qrTranspMOT_CNH: TStringField;
    qrTranspMOT_CNH_CATEG: TStringField;
    qrTranspMOT_CNH_VALID: TDateTimeField;
    qrTranspMOT_PAI: TStringField;
    qrTranspMOT_MAE: TStringField;
    qrTranspMOT_TEL_PESS: TStringField;
    qrTranspMOT_TEL_COM: TStringField;
    qrTranspMOT_PAMCARD: TStringField;
    qrTranspMOT_PAMCARD_VIG: TDateTimeField;
    qrTranspMOT_ENDERECO_COMPL: TStringField;
    qrTranspMOT_ENDERECO_BAIRRO: TStringField;
    qrTranspVEIC_ID: TIntegerField;
    qrTranspMOT_VEIC_PLACA: TStringField;
    qrTranspMOT_VEIC_CIDADE: TStringField;
    qrTranspMOT_VEIC_UF_SIGLA: TStringField;
    qrTranspMOT_VEIC_MARCA: TStringField;
    qrTranspMOT_VEIC_ANO: TStringField;
    qrTranspMOT_VEIC_MODELO: TStringField;
    qrTranspMOT_VEIC_COR: TStringField;
    qrTranspMOT_VEIC_CHASSI: TStringField;
    qrTranspMOT_CARRETA_PLACA: TStringField;
    qrTranspMOT_CARRETA_CIDADE: TStringField;
    qrTranspMOT_CARRETA_UF_SIGLA: TStringField;
    qrTranspMOT_CARRETA_MARCA: TStringField;
    qrTranspMOT_CARRETA_ANO: TStringField;
    qrTranspMOT_CARRETA_MODELO: TStringField;
    qrTranspMOT_CARRETA_COR: TStringField;
    qrTranspMOT_CARRETA_CHASSI: TStringField;
    qrTranspMOT_PAMC_NUM: TStringField;
    qrTranspMOT_NUMPIS: TStringField;
    qrTranspMOT_CARRETA_COMPR: TFloatField;
    qrTranspMOT_CARRETA_LARG: TFloatField;
    qrTranspMOT_CARRETA_ALT: TFloatField;
    qrTranspMOT_CARRETA_M3: TFloatField;
    qrTranspMOT_NEXTEL: TStringField;
    qrTranspMOT_EQUIP: TStringField;
    qrTranspRENAVAN: TStringField;
    qrTranspRNTRC: TStringField;
    QRDBText7: TQRDBText;
    QRDBText8: TQRDBText;
    QRDBText9: TQRDBText;
    procedure FormCreate(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  frmRPA: TfrmRPA;

implementation

uses UfrmConciliacaoFrete, UMenu;

{$R *.DFM}

procedure TfrmRPA.FormCreate(Sender: TObject);
begin
    qrParametro.Open;
end;

procedure TfrmRPA.FormClose(Sender: TObject; var Action: TCloseAction);
begin
   qrParametro.Close;
   qrTransp.Close;
   Action := caFree;
   frmRPA := nil;
end;

end.
