//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmoxEstoqueRetroativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KardexTemp
    {
        public int KAR_ID { get; set; }
        public Nullable<int> MAT_ID { get; set; }
        public Nullable<int> MARCA_ID { get; set; }
        public Nullable<int> LOCAL_ID { get; set; }
        public string N_LOTE { get; set; }
        public Nullable<System.DateTime> VALID { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string TIPO { get; set; }
        public Nullable<double> QTDE { get; set; }
        public Nullable<double> SALDO { get; set; }
        public string USUARIO { get; set; }
        public string USUARIOATIVO { get; set; }
        public Nullable<int> TD_ID { get; set; }
        public string DOCTO { get; set; }
        public Nullable<int> UNI_ID { get; set; }
        public string FOR_CODI { get; set; }
        public Nullable<int> almox_id { get; set; }
    }
}
