//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmoxEstoqueRetroativo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StorageCuraEntities : DbContext
    {
        public StorageCuraEntities()
            : base("name=StorageCuraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Datas> Datas { get; set; }
        public virtual DbSet<KardexTemp> KardexTemp { get; set; }
        public virtual DbSet<stoHistoricoEstoque> stoHistoricoEstoque { get; set; }
        public virtual DbSet<vwKardex> vwKardex { get; set; }
    }
}
