//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmoxEstoqueRetroativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stoHistoricoEstoque
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DataReferencia { get; set; }
        public Nullable<double> QTDE { get; set; }
        public int MAT_ID { get; set; }
        public int GRU_ID { get; set; }
        public Nullable<int> UNI_ID { get; set; }
        public int LOCAL_ID { get; set; }
        public int MARCA_ID { get; set; }
        public Nullable<decimal> REPOSICAO { get; set; }
        public string AUTOMATICO { get; set; }
    }
}
