//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbContext : DbContext
    {
        public dbContext()
            : base("name=dbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MateriaisSimone> MateriaisSimone { get; set; }
        public virtual DbSet<Local> Local { get; set; }
        public virtual DbSet<GRUPO_MATERIAL> GRUPO_MATERIAL { get; set; }
        public virtual DbSet<MATERIAIS> MATERIAIS { get; set; }
    }
}
