//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local
    {
        public int Local_ID { get; set; }
        public string Descricao { get; set; }
        public string DisponivelSN { get; set; }
        public string CONSUMO { get; set; }
        public string CONTROLA_ESTOQUE { get; set; }
    }
}
