//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeitorNFe.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NFe()
        {
            this.NFeProduto = new HashSet<NFeProduto>();
        }
    
        public int IdNFe { get; set; }
        public Nullable<int> IdEmitente { get; set; }
        public Nullable<int> Ambiente { get; set; }
        public Nullable<int> cDV { get; set; }
        public Nullable<int> ide_cUF { get; set; }
        public string ide_natOp { get; set; }
        public Nullable<int> ide_indPag { get; set; }
        public Nullable<int> ide_mode { get; set; }
        public string ide_serie { get; set; }
        public Nullable<int> ide_nNF { get; set; }
        public Nullable<System.DateTime> ide_dEmi { get; set; }
        public Nullable<System.DateTime> ide_dSaiEnt { get; set; }
        public Nullable<int> ide_tpNF { get; set; }
        public Nullable<int> ide_cMunFG { get; set; }
        public Nullable<int> ide_tpImp { get; set; }
        public Nullable<int> ide_finNFe { get; set; }
        public Nullable<int> ide_tpEmis { get; set; }
        public Nullable<int> ide_procEmi { get; set; }
        public string ide_verProc { get; set; }
        public string ide_NFref { get; set; }
        public string ide_CondPagDesc { get; set; }
        public Nullable<int> ide_indFinal { get; set; }
        public Nullable<int> ide_indPres { get; set; }
        public Nullable<int> ide_cNF { get; set; }
        public string dest_CNPJ { get; set; }
        public string dest_CPF { get; set; }
        public string dest_xNome { get; set; }
        public string dest_xFant { get; set; }
        public string dest_xlgr { get; set; }
        public string dest_nro { get; set; }
        public string dest_xCpl { get; set; }
        public string dest_xBairro { get; set; }
        public string dest_cMun { get; set; }
        public string dest_xMun { get; set; }
        public string dest_UF { get; set; }
        public string dest_CEP { get; set; }
        public string dest_cPais { get; set; }
        public string dest_xPais { get; set; }
        public string dest_fone { get; set; }
        public string dest_IE { get; set; }
        public string dest_IESUF { get; set; }
        public string dest_email { get; set; }
        public string dest_indIEDest { get; set; }
        public string dest_IdExtrangeiro { get; set; }
        public Nullable<decimal> tot_vBC { get; set; }
        public Nullable<decimal> tot_vICMS { get; set; }
        public Nullable<decimal> tot_vBCST { get; set; }
        public Nullable<decimal> tot_vST { get; set; }
        public Nullable<decimal> tot_vProd { get; set; }
        public Nullable<decimal> tot_vFrete { get; set; }
        public Nullable<decimal> tot_vSeg { get; set; }
        public Nullable<decimal> tot_vDesc { get; set; }
        public Nullable<decimal> tot_vII { get; set; }
        public Nullable<decimal> tot_vIPI { get; set; }
        public Nullable<decimal> tot_vPIS { get; set; }
        public Nullable<decimal> tot_vCOFINS { get; set; }
        public Nullable<decimal> tot_vOutro { get; set; }
        public Nullable<decimal> tot_vNF { get; set; }
        public Nullable<decimal> tot_vTotTrib { get; set; }
        public Nullable<decimal> tot_vICMSDeson { get; set; }
        public Nullable<decimal> tot_vICMSUFDest_Opc { get; set; }
        public Nullable<decimal> tot_vICMSUFRemet { get; set; }
        public Nullable<decimal> tot_vFCPUFDest { get; set; }
        public Nullable<decimal> tot_vFCP { get; set; }
        public Nullable<decimal> tot_vFCPST { get; set; }
        public Nullable<decimal> tot_vFCPSTRet { get; set; }
        public Nullable<decimal> tot_vIPIDevol { get; set; }
        public string tra_modFrete { get; set; }
        public string tra_CNPJ { get; set; }
        public string tra_CPF { get; set; }
        public string tra_xNome { get; set; }
        public string tra_IE { get; set; }
        public string tra_xEnder { get; set; }
        public string tra_xMun { get; set; }
        public string tra_UF { get; set; }
        public string Recibo { get; set; }
        public string Protocolo { get; set; }
        public Nullable<System.DateTime> DtAutorizacao { get; set; }
        public string MsgRetorno { get; set; }
        public string NFeStatus { get; set; }
        public Nullable<System.DateTime> DtCancelamento { get; set; }
        public string Justificativa { get; set; }
        public string ChaveAut { get; set; }
        public string ProtocoloCancelamento { get; set; }
        public string veic_Placa { get; set; }
        public string veic_UF { get; set; }
        public string veic_RNTC { get; set; }
        public Nullable<decimal> vol_qVol { get; set; }
        public string vol_esp { get; set; }
        public string vol_Marca { get; set; }
        public string vol_nVol { get; set; }
        public Nullable<decimal> vol_pesoL { get; set; }
        public Nullable<decimal> vol_pesoB { get; set; }
        public string vol_lacres { get; set; }
        public string infAdic { get; set; }
        public Nullable<int> IdExterno { get; set; }
        public string pag_tPag { get; set; }
        public Nullable<decimal> pag_vPag { get; set; }
        public string CCeTexto { get; set; }
        public string UFSaidaPais { get; set; }
        public string xLocEmbarq { get; set; }
        public string emi_CNPJ { get; set; }
        public string emi_CPF { get; set; }
        public string emi_xNome { get; set; }
        public string emi_xFant { get; set; }
        public string emi_IE { get; set; }
        public string emi_xLgr { get; set; }
        public string emi_nro { get; set; }
        public string emi_xCpl { get; set; }
        public string emi_xBairro { get; set; }
        public string emi_cMun { get; set; }
        public string emi_xMun { get; set; }
        public string emi_UF { get; set; }
        public string emi_CEP { get; set; }
        public string emi_cPais { get; set; }
        public string emi_xPais { get; set; }
        public string emi_Fone { get; set; }
        public string emi_IEST { get; set; }
        public string emi_IM { get; set; }
        public string emi_CNAE { get; set; }
        public string emi_CRT { get; set; }
        public string emi_xContato { get; set; }
        public string emi_xContatoEmail { get; set; }
        public string emi_idCSRT { get; set; }
        public string emi_CSRT { get; set; }
        public string emi_chaveNFe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NFeProduto> NFeProduto { get; set; }
    }
}
