//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeitorNFe.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFeProduto
    {
        public int IdNFeProduto { get; set; }
        public Nullable<int> IdNFe { get; set; }
        public string cProd { get; set; }
        public string cEAN { get; set; }
        public string xProd { get; set; }
        public string NCM { get; set; }
        public string CEST { get; set; }
        public string CFOP { get; set; }
        public string uCom { get; set; }
        public Nullable<decimal> qCom { get; set; }
        public Nullable<decimal> vUnCom { get; set; }
        public Nullable<decimal> vProd { get; set; }
        public string cEANTrib { get; set; }
        public string uTrib { get; set; }
        public Nullable<decimal> qTrib { get; set; }
        public Nullable<decimal> vUnTrib { get; set; }
        public Nullable<decimal> vOutro { get; set; }
        public Nullable<int> indTot { get; set; }
        public string xPed { get; set; }
        public string ICMS_origem { get; set; }
        public string ICMS_CST { get; set; }
        public Nullable<int> ICMS_modBC { get; set; }
        public Nullable<decimal> ICMS_redBC { get; set; }
        public Nullable<decimal> ICMS_vBC { get; set; }
        public Nullable<decimal> ICMS_pICMS { get; set; }
        public Nullable<decimal> ICMS_vICMS { get; set; }
        public Nullable<int> ICMS_modBCST { get; set; }
        public Nullable<decimal> ICMS_pMVAST { get; set; }
        public Nullable<decimal> ICMS_pRedBCST { get; set; }
        public Nullable<decimal> ICMS_vBCST { get; set; }
        public Nullable<decimal> ICMS_pST { get; set; }
        public Nullable<decimal> ICMS_vST { get; set; }
        public Nullable<decimal> ICMS_vBCSTRet { get; set; }
        public Nullable<decimal> ICMS_vICMSSTRet { get; set; }
        public Nullable<decimal> ICMS_pCredSN { get; set; }
        public Nullable<decimal> ICMS_vCredICMSSN { get; set; }
        public string IPI_CST { get; set; }
        public string IPI_Enq { get; set; }
        public Nullable<decimal> IPI_pIpi { get; set; }
        public Nullable<decimal> IPI_vIPI { get; set; }
        public string PIS_CST { get; set; }
        public Nullable<decimal> PIS_pPis { get; set; }
        public Nullable<decimal> PIS_vPis { get; set; }
        public string COFINS_CST { get; set; }
        public Nullable<decimal> COFINS_pCofins { get; set; }
        public Nullable<decimal> COFINS_vCofins { get; set; }
        public string infAdic { get; set; }
        public Nullable<decimal> vFrete { get; set; }
        public Nullable<decimal> vSeg { get; set; }
        public Nullable<decimal> vDesc { get; set; }
        public Nullable<decimal> IPI_vBC { get; set; }
        public Nullable<decimal> PIS_vBC { get; set; }
        public Nullable<decimal> COFINS_vBC { get; set; }
        public Nullable<decimal> pis_qBCProd { get; set; }
        public Nullable<decimal> pis_vAliqProd { get; set; }
        public Nullable<decimal> cofins_qBCProd { get; set; }
        public Nullable<decimal> cofins_vAliqProd { get; set; }
        public string ipi_CNPJProd { get; set; }
        public string ipi_cSelo { get; set; }
        public Nullable<decimal> ipi_qSelo { get; set; }
        public string ipi_clEnq { get; set; }
        public Nullable<decimal> ipi_qUnid { get; set; }
        public Nullable<decimal> ipi_vUnid { get; set; }
        public Nullable<int> IdExternoItem { get; set; }
    
        public virtual NFe NFe { get; set; }
    }
}
